/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package anti.nganggur;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author akhma
 */
public class Dashboard_Client extends javax.swing.JFrame {
    Login Temp;
    /** 
     * Creates new form Dashboard_Client
     */
    public Dashboard_Client() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        Done_BTN = new javax.swing.JButton();
        Job_BTN = new javax.swing.JButton();
        MyJob_BTN = new javax.swing.JButton();
        Balance_BTN = new javax.swing.JButton();
        Setting_BTN = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 30, 130, 40));

        Done_BTN.setBorder(null);
        Done_BTN.setContentAreaFilled(false);
        Done_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Done_BTNActionPerformed(evt);
            }
        });
        getContentPane().add(Done_BTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 790, 150, 40));

        Job_BTN.setContentAreaFilled(false);
        getContentPane().add(Job_BTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 70, 30));

        MyJob_BTN.setToolTipText("");
        MyJob_BTN.setContentAreaFilled(false);
        MyJob_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MyJob_BTNActionPerformed(evt);
            }
        });
        getContentPane().add(MyJob_BTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 80, 30));

        Balance_BTN.setContentAreaFilled(false);
        Balance_BTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Balance_BTNMouseClicked(evt);
            }
        });
        getContentPane().add(Balance_BTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, 100, 30));

        Setting_BTN.setContentAreaFilled(false);
        Setting_BTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Setting_BTNMouseClicked(evt);
            }
        });
        getContentPane().add(Setting_BTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, 90, 30));

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 540, 40));

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 450, 540, 170));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 650, 540, 40));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 540, 40));

        jLabel3.setText("Id");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 700, -1, -1));

        jLabel4.setText("Nama Pekerjaan");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, -1, -1));

        jLabel5.setText("Jenis Pekerjaan");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, -1, -1));

        jLabel6.setText("Deskripsi Pekerjaan");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 720, 540, 40));

        jLabel7.setText("Tawaran Fee");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 630, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\akhma\\OneDrive\\Pictures\\Saved Pictures\\White.PNG")); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 270, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\akhma\\OneDrive\\Pictures\\Saved Pictures\\Job_Client.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private boolean verify(){
        String judul = jTextField2.getText();
        String jenis = jTextField5.getText();
        String deksripsi = jTextField3.getText();
        String tawaran = jTextField4.getText();
        String kode = jTextField1.getText();
        
        if (judul.trim().equals("") || jenis.trim().equals("") || 
            deksripsi.trim().equals("") || tawaran.trim().equals("") || 
            kode.trim().equals("")) {
            JOptionPane.showMessageDialog(null, "satu diantara fields lain ada yang kosong","Fields Kosong",2);
            return false;
            }else{
            return true;
            
            }
    };
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     new Login().setVisible(true);
     dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Done_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Done_BTNActionPerformed
        String temp =  "whd" ;
        String temp2 = "";
        String sts ="Belum";
        String judul = jTextField2.getText();
        String jenis = jTextField5.getText();
        String deksripsi = jTextField3.getText();
        String tawaran = jTextField4.getText();
        String kode = jTextField1.getText();
        String client = temp;
        String freelancer = temp2;
        String Status = sts;
        
        
        if (verify()) 
        {
            PreparedStatement ps;
            ResultSet rs;
            String registerUserQuery = "INSERT INTO `pekerjaan_client`(`Nama_Pekerjaan`,`Jenis_Pekerjaan`, `Deskripsi_Pekerjaan`,`Tawaran_Fee`,`Id_Pekerjaan`,`Username_Client`,`Username_Freelance`,`Status_Pekerjaan`)VALUES(?,?,?,?,?,?,?,?)";
            
            try {
                      
                      ps = DBConnection.getConnection().prepareStatement(registerUserQuery);
                      ps.setString(1, judul);
                      ps.setString(2, jenis);
                      ps.setString(3, deksripsi);
                      ps.setString(4, tawaran);
                      ps.setString(5, kode);
                      ps.setString(6, client);
                      ps.setString(7, freelancer);
                      ps.setString(8, Status);
                      
                      
                      
                       
                      if(ps.executeUpdate() != 0)
                         {
                             JOptionPane.showMessageDialog(null, "Your Job Has Been Created");
                             new MyJob_Client().setVisible(true);
                             dispose();
                         }else{
                             JOptionPane.showMessageDialog(null, "Error: Check Your Information");
                         }
                      
                  } catch (SQLException ex) {
                      Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
                      
                  }
        }
    }//GEN-LAST:event_Done_BTNActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void MyJob_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MyJob_BTNActionPerformed
    new MyJob_Client().setVisible(true);
    dispose();
    }//GEN-LAST:event_MyJob_BTNActionPerformed

    private void Balance_BTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Balance_BTNMouseClicked
    new Balance_Client().setVisible(true);
    dispose();
    }//GEN-LAST:event_Balance_BTNMouseClicked

    private void Setting_BTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Setting_BTNMouseClicked
    new Settings_Client().setVisible(true);
    dispose();
    }//GEN-LAST:event_Setting_BTNMouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard_Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard_Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard_Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard_Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard_Client().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Balance_BTN;
    private javax.swing.JButton Done_BTN;
    private javax.swing.JButton Job_BTN;
    private javax.swing.JButton MyJob_BTN;
    private javax.swing.JButton Setting_BTN;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
