/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package anti.nganggur;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author akhma
 */
public class Job_Freelance extends javax.swing.JFrame {

    private DefaultTableModel  Table_Client;
    private String SQL; 
    /**
     * Creates new form Job_Freelance
     */
    public Job_Freelance() {
        initComponents();
        this.TampilData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MyJob_BTN = new javax.swing.JButton();
        Balance_BTN = new javax.swing.JButton();
        Setting_BTN = new javax.swing.JButton();
        LogOut_BTN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MyJob_BTN.setBorderPainted(false);
        MyJob_BTN.setContentAreaFilled(false);
        MyJob_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MyJob_BTNActionPerformed(evt);
            }
        });
        getContentPane().add(MyJob_BTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 90, 30));

        Balance_BTN.setBorderPainted(false);
        Balance_BTN.setContentAreaFilled(false);
        Balance_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Balance_BTNActionPerformed(evt);
            }
        });
        getContentPane().add(Balance_BTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 110, 30));

        Setting_BTN.setBorderPainted(false);
        Setting_BTN.setContentAreaFilled(false);
        Setting_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Setting_BTNActionPerformed(evt);
            }
        });
        getContentPane().add(Setting_BTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, 100, 30));

        LogOut_BTN.setBorderPainted(false);
        LogOut_BTN.setContentAreaFilled(false);
        LogOut_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOut_BTNActionPerformed(evt);
            }
        });
        getContentPane().add(LogOut_BTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 30, 130, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Judul", "Jenis", "Deskripsi", "Tawaran_Fee"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 760, 520));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setText("List Pekerjaan Yang Tersedia");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, -1, -1));

        jButton1.setText("Take This Job");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 790, 140, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\akhma\\OneDrive\\Pictures\\Saved Pictures\\White.PNG")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 270, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\akhma\\OneDrive\\Pictures\\Saved Pictures\\Job_Freelance.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

     public void TampilData() {
        Table_Client = new DefaultTableModel();
        Table_Client.addColumn("Judul");
        Table_Client.addColumn("Jenis");
        Table_Client.addColumn("Deskripsi");
        Table_Client.addColumn("Tawaran Fee");
        Table_Client.addColumn("Freelancer");
        Table_Client.addColumn("Status");
        jTable1.setModel(Table_Client);
        Connection conn = DBConnection.getConnection();
        try {
            java.sql.Statement stmt = conn.createStatement();
            SQL = "select * from pekerjaan_client where Status_Pekerjaan = 'Belum'";
            java.sql.ResultSet res = stmt.executeQuery(SQL);
            while (res.next()) {
                Table_Client.addRow(new Object[]{
                    res.getString("Nama_Pekerjaan"),
                    res.getString("Jenis_Pekerjaan"),
                    res.getString("Deskripsi_Pekerjaan"),
                    res.getInt("Tawaran_Fee"),
                    res.getString("Username_Freelance"),
                    res.getString("Status_Pekerjaan")
                });
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }
    private void MyJob_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MyJob_BTNActionPerformed
    new MyJob_Freelance().setVisible(true);
    dispose();
    }//GEN-LAST:event_MyJob_BTNActionPerformed

    private void Balance_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Balance_BTNActionPerformed
    new Balance_Freelance().setVisible(true);
    dispose();
    }//GEN-LAST:event_Balance_BTNActionPerformed

    private void Setting_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Setting_BTNActionPerformed
    new Settings_Freelance().setVisible(true);
    dispose();
    }//GEN-LAST:event_Setting_BTNActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      int position;
        position = this.jTable1.getSelectedRow();
        
        try {
                String updateQuery = "UPDATE pekerjaan_client SET Username_Freelance = 'fahmi'" ;
                String updateQue1 ="UPDATE pekerjaan_client SET Status_Pekerjaan = 'Diambil'" ;
                PreparedStatement preparedStmt = DBConnection.getConnection().prepareStatement(updateQuery);
                PreparedStatement preparedStm1 = DBConnection.getConnection().prepareStatement(updateQue1);

                preparedStmt.execute();
                preparedStm1.execute();
                JOptionPane.showMessageDialog(null, "Pekerjaan Didapatkan");
                new Job_Freelance().setVisible(true);
                this.dispose();
                
            } catch (HeadlessException | SQLException e) {
                System.err.println("Got an exception! ");
                System.err.println(e.getMessage());
            }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void LogOut_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOut_BTNActionPerformed
     new Login().setVisible(true);
     this.dispose();
    }//GEN-LAST:event_LogOut_BTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Job_Freelance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Job_Freelance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Job_Freelance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Job_Freelance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Job_Freelance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Balance_BTN;
    private javax.swing.JButton LogOut_BTN;
    private javax.swing.JButton MyJob_BTN;
    private javax.swing.JButton Setting_BTN;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
